### ISSUE TITLE
cannot sync - get: ImportError: cannot import name lru_cache

### ISSUE THREAD

**Issue by MarshCastle** [ogarcia/trellowarrior#18]
Nice project - I'm struggling to get started with it though :(
I've just followed the README to install TrelloWarrior, but I'm not able to call TrelloWarrior with thh authenticate command.

I have:
```
(trw) marsh@wuji:~$ pip2 show py-trello tasklib
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Name: py-trello
Version: 0.17.1
Summary: Python wrapper around the Trello API
Home-page: https://trello.com/board/py-trello/4f145d87b2f9f15d6d027b53
Author: Richard Kolkovich
Author-email: richard@sigil.org
License: BSD License
Location: /home/marsh/trw/lib/python2.7/site-packages
Requires: pytz, requests, requests-oauthlib, python-dateutil
Required-by: trellowarrior
---
Name: tasklib
Version: 2.2.0
Summary: Python Task Warrior library
Home-page: https://github.com/robgolding63/tasklib
Author: Rob Golding
Author-email: rob@robgolding.com
License: BSD
Location: /home/marsh/trw/lib/python2.7/site-packages
Requires: tzlocal, pytz
Required-by: trellowarrior

```
when authorising I get:
```
(trw) marsh@wuji:~$ trellowarrior auth --api-key 5dc73ba01fd7a7d6b9b06f08b24e0f45 --api-key-secret xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx --expiration 30days --name TrelloWarrior
Traceback (most recent call last):
  File "/home/marsh/trw/bin/trellowarrior", line 5, in <module>
    from trellowarrior.main import main
  File "/home/marsh/trw/local/lib/python2.7/site-packages/trellowarrior/main.py", line 13, in <module>
    from tasklib.task import Task
  File "/home/marsh/trw/local/lib/python2.7/site-packages/tasklib/__init__.py", line 1, in <module>
    from .backends import TaskWarrior
  File "/home/marsh/trw/local/lib/python2.7/site-packages/tasklib/backends.py", line 9, in <module>
    from functools import lru_cache
ImportError: cannot import name lru_cache

```
Have I done something stupid?

**Comment by MarshCastle** [comment]
well.. I fixed that (trellowarrior and tasklib were out of date), then got hit by a missing module "configparser" - installed - but now hit with clients.taskwarrior module missing:
```
$ trellowarrior auth --api-key 5dc73ba01fd7a7d6b9b06f08b24e0f45 --api-key-secret d24ece285b071cb96fc1d241be943ac42e476f2a6a9dea9f9a6923bc13a25e6b --expiration 30days --name TrelloWarrior
Traceback (most recent call last):
  File "/home/marsh/trw/bin/trellowarrior", line 5, in <module>
    from trellowarrior.main import main
  File "/home/marsh/trw/local/lib/python2.7/site-packages/trellowarrior/main.py", line 13, in <module>
    from trellowarrior.commands.sync import sync
  File "/home/marsh/trw/local/lib/python2.7/site-packages/trellowarrior/commands/sync.py", line 9, in <module>
    from trellowarrior.clients.trellowarrior import TrelloWarriorClient
  File "/home/marsh/trw/local/lib/python2.7/site-packages/trellowarrior/clients/trellowarrior.py", line 9, in <module>
    from trellowarrior.clients.taskwarrior import TaskwarriorClient
ImportError: No module named clients.taskwarrior
```
I'm sure I had this going a year or so ago, but it's not working on this system (Debian Buster).

Any help greatly appreciated. Cheers.

**Comment by ogarcia** [comment]
As [say in Readme](https://github.com/ogarcia/trellowarrior#the-easy-way) this is a **Python 3** proyect. So you need use pip in a Python 3 virtualenv (or in your system).

**Comment by MarshCastle** [comment]
OK - got it - thanks very much - it works like a charm :+1: 

Any plans for description sync in the pipeline?

**Comment by ogarcia** [comment]
No, because TaskWarrior don't have a title/description fields. It only have description that is synced with Trello tiltles.
