### ISSUE TITLE
Decoding Unicode

### ISSUE THREAD

**Issue by jean** [ogarcia/trellowarrior#2]
Syncing a board failed with a traceback:

```
Traceback (most recent call last):
  File "./trellowarrior.py", line 411, in <module>
    main()
  File "./trellowarrior.py", line 400, in main
    project['trello_done_list'])
  File "./trellowarrior.py", line 273, in sync_trello_tw
    download_trello_card(project_name, list_name, trello_card, task_warrior, doing_list_name, done_list_name)
  File "./trellowarrior.py", line 183, in download_trello_card
    new_tw_task['description'] = trello_card.name.decode('utf-8')
  File "/home/john/repos/git/trellowarrior/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 29: ordinal not in range(128)
```

I added a breakpoint to look more closely:

```
183         try:
184             new_tw_task['description'] = trello_card.name.decode('utf-8')
185         except:
186             import pdb
187             pdb.set_trace()
188  ->     if trello_card.due_date:
189             new_tw_task['due'] = trello_card.due_date
190         new_tw_task['trelloid'] = trello_card.id
191         new_tw_task['trellolistname'] = list_name.decode('utf-8')
192         new_tw_task.save()
193         if list_name == doing_list_name:
(Pdb) trello_card.name
u'Spicy Boat Noodles at Bangkok\u2019s Victory Monument'
```

So we're trying to _decode_ something that is not encoded. If we encode it first, we can decode it:

```
(Pdb) print trello_card.name
Spicy Boat Noodles at Bangkok’s Victory Monument
(Pdb) print trello_card.name.encode('utf-8')
Spicy Boat Noodles at Bangkok’s Victory Monument
(Pdb) print trello_card.name.encode('utf-8').decode('utf-8')
Spicy Boat Noodles at Bangkok’s Victory Monument
```

My guess is that in the past `py-trello` did not return unicode strings, so it was necessary to decode them first. But now it looks like the `.decode(...)` calls are not necessary.

**Comment by ogarcia** [comment]
Yes, is probably that all `.decode('utf-8')` calls are not necessary with new versions of `py-trello`. If you send me a PR I can merge it, or wait to I have a moment to make a fix ;)
