### ISSUE TITLE
Error when sync deleted card

### ISSUE THREAD

**Issue by henrynvn09** [ogarcia/trellowarrior#20]
After deleting task in taskwarrior, `trellowarrior sync` return this error:
```
Traceback (most recent call last):
  File "/home/username/.local/bin/trellowarrior", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.8/site-packages/trellowarrior/main.py", line 134, in main
    args.func(args)
  File "/home/username/.local/lib/python3.8/site-packages/trellowarrior/commands/sync.py", line 15, in sync
    trellowarrior_client.sync_project(project)
  File "/home/username/.local/lib/python3.8/site-packages/trellowarrior/clients/trellowarrior.py", line 196, in sync_project
    self.trello_client.delete_card(taskwarrior_deleted_task['trelloid'])
AttributeError: 'TrelloClient' object has no attribute 'delete_card'
```
Do I miss any option in `trellowarrior.conf`?
```
[personal]
taskwarrior_project_name = REMIND
trello_board_name = remind
trello_todo_list = To do
trello_doing_list = Doing
trello_done_list = Done
```

**Comment by ogarcia** [comment]
Shit! I do a refactor of function name an broke it. Tomorrow I push new version.

In the meantime, if you wish you can rename `delete_trello_card` in [line 142 of trello.py][1] to `delete_card` to fix.

[1]: https://github.com/ogarcia/trellowarrior/blob/master/trellowarrior/clients/trello.py#L142
